# Generated by Django 5.1.3 on 2024-11-20 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_content', models.TextField(verbose_name='명세서 내용')),
                ('doc_type', models.CharField(choices=[('ppt', 'PowerPoint'), ('excel', 'Excel')], max_length=10, verbose_name='문서 유형')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='상태')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/', verbose_name='생성된 파일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='에러 메시지')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
